### ISSUE TITLE
It seems - Password protection doesn't work correctly

### ISSUE THREAD

**Issue by ZhukDmitry** [antonscheffer/as_zip#2]
Hi.
I used "old" your package without protection. Today I saw new one.
When I set password parameter to add1file, i can read it by PL\SQL, but not WinRAR when I save in to directory.
I get incorrect archive
It can be opened, if it contains unprotected files - you can open it, but when you add protected file you got errors
When open archive
 Unexpected end of archive
When try to open protected file
 Unknown method in <your_file>
 The archive is corrupt

**Comment by unficyp** [comment]
Same problem here - adding a password corrupts the zip file.

**Comment by antonscheffer** [comment]
Latest changes will fix that
