### ISSUE TITLE
Can't compile with use_dbms_crypto = FALSE

### ISSUE THREAD

**Issue by mex-la** [antonscheffer/as_zip#3]
I have no access to dbms_crypto, therefore I set
`use_dbms_crypto       CONSTANT BOOLEAN := FALSE;`
When I compile the body I get
```
LINE/COL ERROR
-------- -----------------------------------------------------------------
414/3    PLS-00103: Encountered the symbol "TYPE" when expecting one of
         the following:
         begin end function pragma procedure
```
Most likely because the TYPE declaration is after the first function.
So I move the five rows up, next to the constant declarations at line 20
Next time I compile I get
```
LINE/COL ERROR
-------- -----------------------------------------------------------------
1503/5   PL/SQL: Statement ignored
1503/14  PLS-00201: identifier 'DBMS_CRYPTO' must be declared
```

The call at this line should not be in the "No dbms_crypto section" of the conditional compilation
`l_mac := dbms_crypto.mac(...`

**Comment by antonscheffer** [comment]
fixed it
