### ISSUE TITLE
ORA-20013: Wrong password provided

### ISSUE THREAD

**Issue by Ayman-Shahrour** [antonscheffer/as_zip#6]
Hello, 
I am using the latest version of as_zip and while I am trying to unzip file protected with a password I'm facing error ORA-20013: Wrong password provided.

my code:
`  as_zip.add1file( g_zipped_blob, l_rec_files.filename, l_rec_files.file_content,'123',null); -- To add file with password
   v_t_file := as_zip.get_file( v_t_dir, v_t_zip, v_zip_files( i ),null,null,null,'123' ) ; -- To unzip the file `

Could you please guide me what is wrong? 

Thanks,
Ayman

**Comment by antonscheffer** [comment]
I somehow forgot a utl_raw.cast_to_raw  in the decryption. I updated the source.

**Comment by Ayman-Shahrour** [comment]
Thank you for your response,
I have tried the latest sources but unfortunately, I get ORA-06502: PL/SQL: numeric or value error: character string buffer too small. any Idea how to fix it?

**Comment by antonscheffer** [comment]
No, because you don't give the full error stack, line number of the error.
Or a clue on what you are trying to do, call add1file, get_file, get_file_list, using a password, ....?

**Comment by Ayman-Shahrour** [comment]
I am facing the following error while unzipping file using get_file:

ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "ICSBPM.AS_ZIP", line 1212
ORA-06512: at "ICSBPM.AS_ZIP", line 1649
ORA-06512: at "ICSBPM.AS_ZIP", line 1664
ORA-06512: at line 13
ORA-06512: at "SYS.DBMS_SQL", line 1721

here is the my code that used to unzip the file:

`Declare
    v_zip_file blob;
    v_zip_files as_zip.file_list;
    v_t_dir varchar2(100) ;
    v_t_zip varchar2(100) ;
    v_t_file blob;
Begin
  v_t_zip := '200.zip';
  v_t_dir := 'DMS';
  v_zip_files  := as_zip.get_file_list( v_t_dir, v_t_zip );
  for i in v_zip_files.first() .. v_zip_files.last
  LOOP 
    v_t_file := as_zip.get_file(p_dir => v_t_dir,
                                           p_zip_file => v_t_zip,
                                           p_file_name => v_zip_files(i), 
                                           p_encoding => null, 
                                           p_nfile_name =>null,
                                           p_idx => null,
                                           p_password => '123') ;
  END LOOP;
End;`

and for zipping the file:

`DECLARE
    FolderName   VARCHAR2(255) := 'DMS'; 
    g_zipped_blob blob;
    filename varchar2(255) := 'bg5.jpg'; -- no issues if it was a small text file
    z_filename varchar2(255) := '200.zip';
BEGIN
  as_zip.add1file( g_zipped_blob, filename , as_zip.File2Blob( FolderName, filename),'123',null);
  as_zip.finish_zip( g_zipped_blob);
  as_zip.save_zip( g_zipped_blob, FolderName , z_filename );
  dbms_lob.freetemporary( g_zipped_blob );
END;` 

Kindly note that I didn't face any issues in case that the zipped file was a small text file ( around 1 K).

Regards,

**Comment by antonscheffer** [comment]
That information helped me to fix an issue with the Winzip encryption, thanks for given the clear error description.

**Comment by Ayman-Shahrour** [comment]
> That information helped me to fix an issue with the Winzip encryption, thanks for given the clear error description.

Hello Antonscheffer,
Thanks for your efforts.
Did you had a chance to fix this issue?

**Comment by antonscheffer** [comment]
As far as I know the issue is fixed. But it is up to you to confirm that your problem is solved :)

**Comment by Ayman-Shahrour** [comment]
Thank you very much... it is working fine now ;)
